--PART A
create or replace type gift_items as table of VARCHAR2(255);
/

create table gift_catalog (gift_ID NUMBER Primary Key, min_purchase number, gifts gift_items)
nested table gifts store as gifts_storage;
/
insert into gift_catalog values(1,100, gift_items('Stickers', 'Pen set'));
insert into gift_catalog values(2,1000, gift_items('Teddy Bear', 'Mug', 'Perfume Sample'));
insert into gift_catalog values(3,10000, gift_items('Backpack', 'Thermos Bottle', 'Chocolate Collection'));

/
--PART B
create table customer_rewards (
    reward_id number generated by default as identity Primary Key, 
    customer_email varchar2(255), 
    gift_id number, 
    reward_date date default sysdate,
    constraint fk_reward_gift
        foreign key (gift_id)
        references gift_catalog(gift_id));
/

--PART C

create or replace package CUSTOMER_MANAGER is
    function GET_TOTAL_PURCHASE(p_customer_id number) return number;
    procedure ASSIGN_GIFTS_TO_ALL;
end CUSTOMER_MANAGER;
/
create or replace package body CUSTOMER_MANAGER is

    function GET_TOTAL_PURCHASE(p_customer_id number) return number is
        v_total_price number;
    begin
        select sum(oi.UNIT_PRICE*oi.quantity) into v_total_price
        from customers c, orders o, order_items oi
        where c.CUSTOMER_ID = o.CUSTOMER_ID and 
              o.ORDER_ID = oi.ORDER_ID and
              o.CUSTOMER_ID = p_customer_id;
        return v_total_price;
    end;

    function CHOOSE_GIFT_PACKAGE(p_total_purchase number) return number is
        v_gift_id number;
    BEGIN
        select gift_id into v_gift_id
        from (select gift_id from GIFT_CATALOG where MIN_PURCHASE <= p_total_purchase order by min_purchase desc)
        where rownum = 1;
        return v_gift_id;
    exception 
        when no_data_found then
            return null;
    end;

    procedure ASSIGN_GIFTS_TO_ALL is
        v_total_price number;
        v_gift_id number;
    begin
        for c in (select EMAIL_ADDRESS, CUSTOMER_ID from customers)
        loop 
            v_total_price := get_total_purchase(c.customer_id);
            v_gift_id := choose_gift_package(v_total_price);
            insert into CUSTOMER_REWARDS (customer_email, gift_id, reward_date) 
            values(c.EMAIL_ADDRESS, v_gift_id, sysdate);
        end loop;
        return;
    end;
end CUSTOMER_MANAGER;
/

--PART D

begin
CUSTOMER_MANAGER.ASSIGN_GIFTS_TO_ALL;
end;
/
select * from customer_rewards cr, GIFT_CATALOG gc where cr.gift_id = gc.gift_id order by reward_id;